### ISSUE TITLE
User Stories

### ISSUE THREAD

**Issue by C-Carr22** [stfc-aeg/timeslice-camera#20]
As a user I need to be able to input my email address and movie code so that I can receive my video by my email

**Comment by C-Carr22** [comment]
As a visitor I need to be able to easily understand the user interface so that I can easily input my email address and movie code

**Comment by C-Carr22** [comment]
As a programmer I need to make sure the personal data of visitors and their videos is not kept forever so that no GDPR laws are broken

**Comment by C-Carr22** [comment]
As a user I want to be able to input multiple video codes so that I can receive all of my videos in one email.

**Comment by timcnicholls** [comment]
Closing as completed
